import CategoryListingHeader from "@/app/components/CategoryListingPage.jsx/CategoryListingHeader"
export const metadata = {
  title: "Category-Listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased `}
      >
        <CategoryListingHeader />
        {children}
      </body>
    </html>
  );
}
