import PricingHeader from "../components/PricingComponent/PricingHeader";

export const metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased `}
      >
        <PricingHeader />
        {children}
      </body>
    </html>
  );
}
