import BusinessRegistrationHeader from "../components/BusinessRegistration/BusinessRegistrationHeader";
export const metadata = {
  title: "Business-Registration-Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased `}>
        <BusinessRegistrationHeader />
        {children}
      </body>
    </html>
  );
}
