import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/HomePage/Footer";
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '700'], // adjust weights as needed
  variable: '--font-nunito',
  display: 'swap',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased bg-[#eaeef4]`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
